Project_Fourm/Controllers/ModeratorController.cs
using Microsoft.AspNetCore.Mvc;
using Project_Forum.Models;
using Project_Forum.Models.Entities;
using Project_Forum.Services.Moderator;
using System.Security.Claims;

namespace Project_Forum.Controllers
{
    public class ModeratorController : Controller
    {

        private readonly ForumProjectContext Context;

        private readonly IModeratorService ModeratorService;

        public ModeratorController(ForumProjectContext context, IModeratorService moderatorService)
        {
            Context = context;
            ModeratorService = moderatorService;
        }
        public async Task<IActionResult> Index(List<ReportDisplayContent> reportDisplayContent)
        {
            reportDisplayContent = await ModeratorService.RetriveNotSolvedReports();
            return View(reportDisplayContent);
        }


        public async Task<IActionResult> Remove(int reportId, int contentId, string contentType)
        {

            await ModeratorService.Delete(reportId, contentId, User.FindFirstValue("UserId"), contentType);
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Keep(int reportId)
        {
            await ModeratorService.Keep(reportId, User.FindFirstValue("UserId"));
            return RedirectToAction("Index");
        }
    }
}

Project_Fourm/Views/Moderator/Index.cshtml
@model List<ReportDisplayContent>
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Moderator</title>

    <link rel="stylesheet" href="~/css/ModeratorIndex.css" />
</head>

@foreach(var reportedContent in Model){

    <div class="single-report-display">
        <div class="report-content">
            <p>@reportedContent.Content</p>
        </div>
        <div class="report-reason">
            <p>@reportedContent.Reason</p>
        </div>
        <form method="POST" asp-controller="Moderator" asp-action="Remove">
            <input type="hidden" name="reportId" value="@reportedContent.ReportId">
            <input type="hidden" name="contentId" value="@reportedContent.ContentId">
            <input type="hidden" name="contentType" value="@reportedContent.ContentType">
            <button type="submit" id="delete-post">
                <i class="material-icons">delete</i>
            </button>
        </form>
        <form method="POST" asp-controller="Moderator" asp-action="Keep">
            <input type="hidden" name="reportId" value="@reportedContent.ReportId">
            <button type="submit" id="keep-post">
                <i class="material-icons">check_circle</i>
            </button>
        </form>
    </div>

}