Project_Fourm/Models/Entities/Tag.cs
using System;
using System.Collections.Generic;

namespace Project_Forum.Models.Entities;

public partial class Tag
{
    public string TagName { get; set; } = null!;

    public virtual ICollection<Post> Posts { get; set; } = new List<Post>();

    public virtual ICollection<ApplicationUser> Users { get; set; } = new List<ApplicationUser>();
}

Project_Fourm/Models/Tag.cs
using System;
using System.Collections.Generic;

namespace Project_Forum.Models;

public partial class Tag
{
    public string TagName { get; set; } = null!;
}

Project_Fourm/Controllers/ForumController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http.Extensions;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Mono.TextTemplating;
using Project_.Models;
using Project_Forum.Models;
using Project_Forum.Models.Entities;
using Project_Forum.Services.ActionButtons;
using Project_Forum.Services.Observe;
using Project_Forum.Services.PostCreation;
using Project_Forum.Services.RetriveContent;
using Project_Forum.Services.Upvoting;
using System.Diagnostics;
using System.Security.Claims;

namespace Project_Forum.Controllers
{
    public class ForumController : Controller
    {
        private readonly IPostCreationService PostService;

        private readonly IActionButtonsService ActionButtonsService;

        private readonly IObserveService ObserveService;

        private readonly IRetriveContentService RetriveContentService;

        private readonly IUpvotingService UpvotingService;


        public ForumController(IPostCreationService postService, IObserveService observeService,
        IActionButtonsService actionButtonsService, 
        IRetriveContentService retriveContentService,
        IUpvotingService upvotingService)
        {
            PostService = postService;
            ActionButtonsService = actionButtonsService;
            ObserveService = observeService;
            RetriveContentService = retriveContentService;
            UpvotingService = upvotingService;

        }

        public async Task<IActionResult> Index(PostCompositeModel model)
        {
            // Assigning the value here so we only use FindFirstValue once instead of once per post/respond in foreach loop
            model.CurrentUserId = User.FindFirstValue("UserId");

            var date = model.FilterPostsModel.GetDateDiffFromCurrentDate();
            var posts = await RetriveContentService.RetrivePostContentAsync(15, date);
            foreach (var post in posts)
            {
                var respond = await RetriveContentService.RetriveRespondContentAsync(post.PostId);
                model.PostDisplayContents.Add((post, respond));
            }

            // if (User.IsInRole("Admin"))
            //   return View("AdminIndex");
            if (User.IsInRole("Moderator"))
                return RedirectToAction("Index", "Moderator");
            else if (User.IsInRole("User"))
                return View("UserIndex", model);
            else
                return View("GuestIndex", model);
        }

        [HttpGet]
        public async Task<IActionResult> LogOut()
        {

            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            return RedirectToAction("Login", "Account");
        }
        [HttpPost]
        [Authorize]
        public async Task<IActionResult> CreatePost(PostCompositeModel model)
        {
            // we don't use ModelState.IsValid because FK User is not Explicitly set in model
            if (User.FindFirstValue("UserId") is not null && !String.IsNullOrEmpty(model.PostModel.PostContent))
            {
                int postId = await PostService.AddPostAsync(User.FindFirstValue("UserId"), model.PostModel.PostContent);
                var tags = await PostService.AddTagsAsync(model.PostModel.PostContent);
                await PostService.AddPostTagsAsync(postId, tags);
                // redirect to same page we're currently on 
                string referringUrl = HttpContext.Request.Headers["Referer"].ToString();
                return Redirect(referringUrl);
            }
            else
            {
                return NoContent();
            }

        }
        [HttpPost]
        [Authorize]
        public async Task<IActionResult> ManageUpvote(int postId)
        {
            if (User.FindFirstValue("UserId") is not null)
            {
                await UpvotingService.ManageUpvoteAsync(User.FindFirstValue("UserId"), postId);
                return StatusCode(201);
            }
            else
            {
                return NoContent();
            }
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> CreateRespond(PostCompositeModel model, int postId)
        {
            // we don't use ModelState.IsValid because FK User is not Explicitly set in model
            if (User.FindFirstValue("UserId") is not null && !String.IsNullOrEmpty(model.RespondModel.RepondContent))
            {
                await PostService.AddRespondAsync(postId, User.FindFirstValue("UserId"), model.RespondModel.RepondContent);

                // redirect to same page we're currently on 
                string referringUrl = HttpContext.Request.Headers["Referer"].ToString();
                return Redirect(referringUrl);
            }
            else
            {
                return NoContent();
            }

        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> ManageRespondUpvote(int respondId)
        {
            if (User.FindFirstValue("UserId") is not null)
            {
                await UpvotingService.ManageRespondUpvoteAsync(User.FindFirstValue("UserId"), respondId);
                return StatusCode(201);
            }
            else
            {
                return NoContent();
            }
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> DeletePost(int postId)
        {
            if (User.FindFirstValue("UserId") is not null)
            {
                await ActionButtonsService.RemovePost(postId);

                // redirect to same page we're currently on 
                string referringUrl = HttpContext.Request.Headers["Referer"].ToString();
                return Redirect(referringUrl);

            }
            return NoContent();
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> DeleteRespond(int respondId)
        {
            if (User.FindFirstValue("UserId") is not null)
            {
                await ActionButtonsService.RemoveRespond(respondId);

                // redirect to same page we're currently on 
                string referringUrl = HttpContext.Request.Headers["Referer"].ToString();
                return Redirect(referringUrl);

            }
            return NoContent();
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Report(int contentId, string reportReason, string contentType)
        {
            var userId = (User.FindFirstValue("UserId"));
            if (userId is not null)
            {
                await ActionButtonsService.ReportContent(contentId, userId, reportReason, contentType);

                // redirect to same page we're currently on 
                string referringUrl = HttpContext.Request.Headers["Referer"].ToString();
                return Redirect(referringUrl);
            }
            return NoContent();
        }

        [HttpPut]
        [Authorize]
        public async Task<IActionResult> Edit(int contentId, string newContent, string contentType)
        {
            var userId = (User.FindFirstValue("UserId"));
            if (userId is not null)
            {
                await ActionButtonsService.EditContent(contentId, newContent, contentType);
                return Ok();
            }
            return NotFound();
        }

        [HttpGet]
        public async Task<IActionResult> Tag(PostCompositeModel model, string tag)
        {

            var result = await ObserveService.IsTagObserved(tag, User.FindFirstValue("UserId"));
            if (result == true)
                model.visibility = "visibility_off";
            else
                model.visibility = "visibility";

            // Assigning the value here so we only use FindFirstValue once instead of once per post/respond in foreach loop
            model.CurrentUserId = User.FindFirstValue("UserId");
            var date = model.FilterPostsModel.GetDateDiffFromCurrentDate();
            var posts = await RetriveContentService.RetrivePostsByTag(15, date, tag);
            foreach (var post in posts)
            {
                var respond = await RetriveContentService.RetriveRespondContentAsync(post.PostId);
                model.PostDisplayContents.Add((post, respond));
            }
            if (User.IsInRole("User"))
                return View("Tag", model);
            else
                return View("GuestTag", model);
        }

        [HttpPost]
        public async Task<IActionResult> Observe(string tagName)
        {

            var result = await ObserveService.HandleTagObservation(tagName, User.FindFirstValue("UserId"));
            if (result == true)
            {
                // redirect to same page we're currently on 
                string referringUrl = HttpContext.Request.Headers["Referer"].ToString();
                return Redirect(referringUrl);
            }
            return NoContent();

        }

        [HttpGet]
        public async Task<IActionResult> Feed(PostCompositeModel model)
        {


            // Assigning the value here so we only use FindFirstValue once instead of once per post/respond in foreach loop
            model.CurrentUserId = User.FindFirstValue("UserId");
            var date = model.FilterPostsModel.GetDateDiffFromCurrentDate();
            var posts = await RetriveContentService.RetriveFeed(15, date, User.FindFirstValue("UserId"));
            foreach (var post in posts)
            {
                var respond = await RetriveContentService.RetriveRespondContentAsync(post.PostId);
                model.PostDisplayContents.Add((post, respond));
            }
            return View("Feed", model);
           
        }
    

Project_Fourm/Views/Forum/AdminIndex.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

Project_Fourm/Views/Forum/Feed.cshtml
@model PostCompositeModel

@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    <div class="send-post-form">
        <form method="POST" asp-controller="Forum" asp-action="CreatePost">
            <textarea id="post-message" placeholder="Create a new post..." asp-for="PostModel.PostContent"></textarea>
            <button type="submit" id="send-post-button" value="x" >
                <i class="material-icons">send</i>
            </button>
        </form>
    </div>

    
    <dialog class="modal" id="modal">
        <h2>Report details</h2>
        <textarea placeholder="200 characters..." maxlength="200" data-contentid="" data-contenttype=""></textarea>
        <button type="submit" id="send-report-details" value="x">
            <i class="material-icons">send</i>
        </button>
    </dialog>

    <dialog class="modal" id="edit-modal">
        <h2>Edit Post</h2>
        <textarea placeholder="Edit content..." data-contentid="" data-contenttype=""></textarea>
        <button type="submit" id="edit-button" value="x">
            <i class="material-icons">send</i>
        </button>
    </dialog>



    <div class="display-post">
        <div class="filters">
            @using (Html.BeginForm("Feed", "Forum", FormMethod.Get))
            {
        
                <div class="choose-hour-filter">
                    <label class="radio-button-label">
                        @Html.RadioButtonFor(model => model.FilterPostsModel.SelectedTimeFilter, TimeFilter.sixHours,
                        new {@class = "radio-button-style"})
                            <span class="label-text">6h</span>
                    </label>
                    <label class="radio-button-label">
                        @Html.RadioButtonFor(model => model.FilterPostsModel.SelectedTimeFilter, TimeFilter.twelveHours, 
                    new {@class = "radio-button-style"})
                            <span class="label-text">12h</span>
                    </label>
                    <label class="radio-button-label"> 
                        @Html.RadioButtonFor(model => model.FilterPostsModel.SelectedTimeFilter, TimeFilter.day,
                    new {@class = "radio-button-style"})
                            <span class="label-text">day</span>
                    </label>
                    <label class="radio-button-label">
                        @Html.RadioButtonFor(model => model.FilterPostsModel.SelectedTimeFilter, TimeFilter.week,
                    new {@class = "radio-button-style"})
                            <span class="label-text">week</span>
                    </label>
                    <label class="radio-button-label"> 
                        @Html.RadioButtonFor(model => model.FilterPostsModel.SelectedTimeFilter, TimeFilter.month,
                    new {@class = "radio-button-style"})
                            <span class="label-text">month</span>
                    </label>
                </div>
       
            }
        </div>

        <div class="display-post-container">
            @foreach(var postDisplay in Model.PostDisplayContents)
        {
                <div class="single-post-display">
                    <p class="post-username">@postDisplay.Item1.Username</p>
                    <p class="post-content">@postDisplay.Item1.Content</p>
                    <p class="post-creation-date">@postDisplay.Item1.CreationDate</p>
                    <input type="checkbox" class="post-upvote-checkbox" data-postid="@postDisplay.Item1.PostId">
                    <i id="post-upvote-favorite" class="material-icons">favorite</i>
                    <span class="post-upvote-count">@postDisplay.Item1.UpvotesCount</span>

                @if (Model.CurrentUserId == postDisplay.Item1.UserId)
            {
                    <form method="POST" asp-controller="Forum" asp-action="DeletePost">
                        <input type="hidden" name="postId" value="@postDisplay.Item1.PostId">
                        <button type="submit" name="action" id="post-delete-button" value="deletePost">
                            <i class="material-icons">delete</i>
                        </button>
                    </form>

                    <button type="submit" name="action" class="edit-button"
                        data-contentid="@postDisplay.Item1.PostId"
                        data-contenttype="Post" value="reportPost">
                        <i class="material-icons">edit</i>
                    </button>
            }
            else
            {
                    <button type="submit" name="action" class="post-report-button"
                        data-contentid="@postDisplay.Item1.PostId"
                        data-contenttype="post" value="reportPost">
                            <i class="material-icons">flag</i>
                    </button>
            }
                </div>

                <div class="send-respond-form">
                    <form method="POST" asp-controller="Forum" asp-action="CreateRespond">
                        <input type="hidden" name="postId" value="@postDisplay.Item1.PostId">
                        <textarea id="respond-message" placeholder="Respond..." asp-for="RespondModel.RepondContent"></textarea>
                        <button type="submit" id="send-respond-button" value="x" >
                            <i class="material-icons">send</i>
                        </button>
                    </form>
                </div>

            

                    @foreach (var respondDisplay in postDisplay.Item2)
                {

                        <div class="single-respond-display">
                            <p class="respond-username">@respondDisplay.Username</p>
                            <p class="respond-content">@respondDisplay.Content</p>
                            <p class="respond-creation-date">@respondDisplay.CreationDate</p>
                            <input type="checkbox" class="respond-upvote-checkbox" data-respondid="@respondDisplay.RespondId">
                            <i id="respond-upvote-favorite" class="material-icons">favorite</i>
                            <span class="respond-upvote-count">@respondDisplay.UpvotesCount</span>


                            @if (Model.CurrentUserId == respondDisplay.UserId)
                        {
                                <form method="POST" asp-controller="Forum" asp-action="DeleteRespond">
                                    <input type="hidden" name="respondId" value="@respondDisplay.RespondId">
                                    <button type="submit" name="action" id="respond-delete-button" value="deleteRespond">
                                        <i class="material-icons">delete</i>
                                    </button>
                                </form>

                                <button type="submit" name="action" class="edit-button"
                                    data-contentid="@respondDisplay.RespondId"
                                    data-contenttype="Respond" value="reportRespond">
                                    <i class="material-icons">edit</i>
                                </button>
                        }
                        else
                        {
                                <input type="hidden" name="respondId" value="@respondDisplay.RespondId">
                                <button type="submit" name="action" class="respond-report-button" 
                                    data-contentid="@respondDisplay.RespondId"
                                    data-contenttype="respond" value="reportRespond">
                                        <i class="material-icons">flag</i>
                                </button>
                        }
                        </div>  
                }
        }
        </div>
                                        

    </div>
}
@section scripts {
    <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
    <script src="~/js/PostUpvote.js"></script>
    <script src="~/js/StorePostUpvote.js"></script>
    <script src="~/js/RespondUpvote.js"></script>
    <script src="~/js/StoreRespondUpvote.js"></script>
    <script src="~/js/ReportModal.js"></script>
    <script src="~/js/EditModal.js"></script>
    <script src="~/js/RefreshOnChangeDate.js"></script>
}

    

Project_Fourm/Views/Forum/GuestIndex.cshtml
@model PostCompositeModel

@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    Layout = "_SidebarLayoutIndexLoggedOut";
    <div class="display-post">
        <div class="filters">
            @using (Html.BeginForm("Index", "Forum", FormMethod.Post))
            {
                <div class="choose-hour-filter">
                    <label class="radio-button-label">
                        @Html.RadioButtonFor(model => model.FilterPostsModel.SelectedTimeFilter, TimeFilter.sixHours,
                new {@class = "radio-button-style"})
                        <span class="label-text">6h</span>
                    </label>
                    <label class="radio-button-label">
                        @Html.RadioButtonFor(model => model.FilterPostsModel.SelectedTimeFilter, TimeFilter.twelveHours,
                new {@class = "radio-button-style"})
                        <span class="label-text">12h</span>
                    </label>
                    <label class="radio-button-label">
                        @Html.RadioButtonFor(model => model.FilterPostsModel.SelectedTimeFilter, TimeFilter.day,
                new {@class = "radio-button-style"})
                        <span class="label-text">day</span>
                    </label>
                    <label class="radio-button-label">
                        @Html.RadioButtonFor(model => model.FilterPostsModel.SelectedTimeFilter, TimeFilter.week,
                new {@class = "radio-button-style"})
                        <span class="label-text">week</span>
                    </label>
                    <label class="radio-button-label">
                        @Html.RadioButtonFor(model => model.FilterPostsModel.SelectedTimeFilter, TimeFilter.month,
                new {@class = "radio-button-style"})
                        <span class="label-text">month</span>
                    </label>
                </div>

            }
            @using (Html.BeginForm("Tag", "Forum", FormMethod.Get))
            {
                <div class="search-container">
                    <input type="text" id="search-input" name="tag" maxlength="50" placeholder="Choose tag...">
                    <button class="search-button" value="search">
                        <i class="material-icons">search</i>
                    </button>
                </div>
            }
        </div>

        <div class="display-post-container">
            @foreach (var postDisplay in Model.PostDisplayContents)
            {
                <div class="single-post-display">
                    <p class="post-username">@postDisplay.Item1.Username</p>
                    <p class="post-content">@postDisplay.Item1.Content</p>
                    <p class="post-creation-date">@postDisplay.Item1.CreationDate</p>
                    <i id="post-upvote-favorite" class="material-icons">favorite</i>
                    <span class="post-upvote-count">@postDisplay.Item1.UpvotesCount</span>
                </div>
                @foreach (var respondDisplay in postDisplay.Item2)
                {

                    <div class="single-respond-display">
                        <p class="respond-username">@respondDisplay.Username</p>
                        <p class="respond-content">@respondDisplay.Content</p>
                        <p class="respond-creation-date">@respondDisplay.CreationDate</p>
                        <i id="respond-upvote-favorite" class="material-icons">favorite</i>
                        <span class="respond-upvote-count">@respondDisplay.UpvotesCount</span>
                    </div>
                }
            }
        </div>


    </div>
}
@section scripts {
    <script src="~/js/RefreshOnChangeDate.js"></script>
}

Project_Fourm/Views/Forum/GuestTag.cshtml
@model PostCompositeModel

@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    <div class="tag-sidebar">
        <p id="current-tag-name">@ViewContext.HttpContext.Request.Query["tag"]</p>
    </div>

    Layout = "_SidebarLayoutIndexLoggedOut";
    <div class="display-post">
        <div class="filters">
            @using (Html.BeginForm("Tag", "Forum", FormMethod.Get))
            {
                // retrives previous tag so changing filter won't change tag we're currently on to empty string
                @Html.Hidden("tag", ViewContext.HttpContext.Request.Query["tag"])
                <div class="choose-hour-filter">
                    <label class="radio-button-label">
                        @Html.RadioButtonFor(model => model.FilterPostsModel.SelectedTimeFilter, TimeFilter.sixHours,
                new {@class = "radio-button-style"})
                        <span class="label-text">6h</span>
                    </label>
                    <label class="radio-button-label">
                        @Html.RadioButtonFor(model => model.FilterPostsModel.SelectedTimeFilter, TimeFilter.twelveHours,
                new {@class = "radio-button-style"})
                        <span class="label-text">12h</span>
                    </label>
                    <label class="radio-button-label">
                        @Html.RadioButtonFor(model => model.FilterPostsModel.SelectedTimeFilter, TimeFilter.day,
                new {@class = "radio-button-style"})
                        <span class="label-text">day</span>
                    </label>
                    <label class="radio-button-label">
                        @Html.RadioButtonFor(model => model.FilterPostsModel.SelectedTimeFilter, TimeFilter.week,
                new {@class = "radio-button-style"})
                        <span class="label-text">week</span>
                    </label>
                    <label class="radio-button-label">
                        @Html.RadioButtonFor(model => model.FilterPostsModel.SelectedTimeFilter, TimeFilter.month,
                new {@class = "radio-button-style"})
                        <span class="label-text">month</span>
                    </label>
                </div>

            }
            @using (Html.BeginForm("Tag", "Forum", FormMethod.Get))
            {
                <div class="search-container">
                    <input type="text" id="search-input" name="tag" max="50" placeholder="Choose tag...">
                    <button class="search-button" value="search">
                        <i class="material-icons">search</i>
                    </button>
                </div>
            }
        </div>
        

        <div class="display-post-container">
            @foreach (var postDisplay in Model.PostDisplayContents)
            {
                <div class="single-post-display">
                    <p class="post-username">@postDisplay.Item1.Username</p>
                    <p class="post-content">@postDisplay.Item1.Content</p>
                    <p class="post-creation-date">@postDisplay.Item1.CreationDate</p>
                    <i id="post-upvote-favorite" class="material-icons">favorite</i>
                    <span class="post-upvote-count">@postDisplay.Item1.UpvotesCount</span>
                </div>
                @foreach (var respondDisplay in postDisplay.Item2)
                {

                    <div class="single-respond-display">
                        <p class="respond-username">@respondDisplay.Username</p>
                        <p class="respond-content">@respondDisplay.Content</p>
                        <p class="respond-creation-date">@respondDisplay.CreationDate</p>
                        <i id="respond-upvote-favorite" class="material-icons">favorite</i>
                        <span class="respond-upvote-count">@respondDisplay.UpvotesCount</span>
                    </div>
                }
            }
        </div>


    </div>
}
@section scripts {
    <script src="~/js/RefreshOnChangeDate.js"></script>
}

Project_Fourm/Views/Forum/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    
    <div class="send-post-form">
        <form action="POST">
            <textarea id="post-message" placeholder="Create a new post..."></textarea>
            <button type="submit" id="send-post-button" value="x">
                <i class="material-icons">send</i>
            </button>
        </form>
    </div>

}

Project_Fourm/Views/Forum/LogOut.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    Layout = "_SidebarLayoutLoggedOutUser";

}

Project_Fourm/Views/Forum/Login.cshtml
@model LoginModel
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    Layout = "_SidebarLayoutLoggedOutUser";


    <div class="main-login-container">
        <form asp-controller="Forum" asp-action="Login" method="post">
            <h2 id="login-header">Sign in</h2>
            <div class="login-class">
                <input type="text" placeholder="Username" asp-for="Username" />
                <i></i>
            </div>
            <div class="login-class" id="login-password">
                <input type="password" placeholder="Password" asp-for="Password" />
                <i></i>
            </div>
            <div id="forgot-passwd">
                <a href="#">Forgot password</a>
            </div>
            <input id="login-submit" type="submit" value="Login" />
            <span asp-validation-for="Username" class="login-error-message"></span>
            <span asp-validation-for="Password" class="login-error-message"></span>
        </form>
    </div>

   
}

Project_Fourm/Views/Forum/Register.cshtml
@model RegisterModel
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    Layout = "_SidebarLayoutLoggedOutUser";




    <div class="main-register-container">
        <form asp-controller="Forum" asp-action="Register" method="post">
            <h2 id="register-header">Sign up</h2>
            <div class="register-class">
                <input type="text" placeholder="Username" asp-for="Username" />
                <i></i>
            </div>
            <div class="register-class" id="register-password">
                <input type="password" placeholder="Password" asp-for="Password" />
                <i></i>
            </div>
            <div class="register-class" id="register-email">
                <input type="email" placeholder="E-Mail" asp-for="Email"  />
                <i></i>
            </div>
            <div class="register-class" id="register-email">
                <input type="date" asp-for="Date"/>
                <i></i>
            </div>
            <input id="register-submit" type="submit" value="Register" />
            <span asp-validation-for="Username" class="register-error-message"></span>
            <span asp-validation-for="Password" class="register-error-message"></span>
            <span asp-validation-for="Email" class="register-error-message"></span>
            <span asp-validation-for="Date" class="register-error-message"></span>
        </form>
    </div>
}